# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20170214_1410'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hits',
            new_name='Hit',
        ),
    ]
