# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_currentevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instanceUrl', models.CharField(max_length=5)),
                ('scheduledStart', models.DateTimeField()),
                ('actualStart', models.DateTimeField()),
                ('scheduledEnd', models.DateTimeField()),
                ('actualEnd', models.DateTimeField()),
                ('done', models.BooleanField()),
                ('active', models.BooleanField()),
                ('name', models.CharField(max_length=200)),
                ('speaker', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='schedulerInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=5)),
            ],
        ),
    ]
