# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_event_schedulerinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentevent',
            name='instanceUrl',
            field=models.CharField(default='zzzzz', max_length=5),
            preserve_default=False,
        ),
    ]
