# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='active',
        ),
        migrations.AddField(
            model_name='schedulerinstance',
            name='activeEvent',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
