# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_currentevent_instanceurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='actualEnd',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='actualStart',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='scheduledEnd',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='scheduledStart',
            field=models.IntegerField(),
        ),
    ]
