# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 16:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_auto_20170222_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulerinstance',
            name='lastAccessed',
            field=models.DateField(default=datetime.date(2017, 2, 23)),
            preserve_default=False,
        ),
    ]
