# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0003_schedulerinstance_lastaccessed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentevent',
            name='instanceUrl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timer.schedulerInstance'),
        ),
        migrations.AlterField(
            model_name='event',
            name='instanceUrl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timer.schedulerInstance'),
        ),
    ]
